name = "Jojo"
uuid = "32629f54-102d-4dab-a32d-ea6cf4ff2719"
authors = ["jumerckx <julesmerckx12@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
